services:
  - type: web
    name: music-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn musicproject.wsgi"
    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src